version: "3.9"
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: immunization
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    build: .
    environment:
      DATABASE_URL: mysql://root:root@db:3306/immunization
      JWT_SECRET: supersecret
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
